<a href="https://colab.research.google.com/github/iamkhan49/heart-disease-prediction-ml/blob/main/Heart_Disease_Detection_using_Classification_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ❤️ Heart Disease Detection using Classification Algorithms

## Machine Learning Classification Project

### Dataset
Heart Disease Dataset

### Objective
Build a Machine Learning model that predicts whether a patient has heart disease based on medical attributes.

### Algorithm
Logistic Regression

### Developed By


*   Anas Ahmad Khan
*   Khwaja Danish oddin


*   Abdul Imran
*   Syed Faisal




*   Hamza Ansari
*   Danish Khan

# ❤️ Heart Disease Detection using Classification Algorithms

## Machine Learning Classification Project

### Dataset
Heart Disease Dataset

### Objective
Build a Machine Learning model that predicts whether a patient has heart disease based on medical attributes.

### Algorithm
Logistic Regression

### Developed By


*   Anas Ahmad Khan
*   Khwaja Danish oddin


*   Abdul Imran
*   Syed Faisal




*   Hamza Ansari
*   Danish Khan

# Project Objective

The objective of this project is to develop a Machine Learning classification model that predicts the presence of heart disease using patient medical information.

This project includes:

- Data Loading
- Data Cleaning
- Exploratory Data Analysis (EDA)
- Feature Engineering
- Feature Selection
- Model Training
- Model Evaluation
- Hyperparameter Tuning
- Prediction on New Data
- Model Saving

In [1]:
# Import Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

import warnings
warnings.filterwarnings("ignore")

plt.style.use("ggplot")

%matplotlib inline

# Upload Dataset

Upload the **heart_disease_dataset.csv** file from your computer.

In [2]:
uploaded = files.upload()

Saving heart_disease_dataset.csv to heart_disease_dataset.csv

In [3]:
df = pd.read_csv("heart_disease_dataset.csv")

# Display First Five Records

In [4]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,heart_disease
0,58,1,1,134,246,0,0,155,0,0.4,1,1,2,1
1,52,0,2,112,245,0,0,143,1,0.1,0,0,3,1
2,59,0,2,126,196,0,0,162,1,1.1,1,0,1,1
3,67,1,1,165,201,0,0,180,0,0.4,2,0,2,0
4,51,1,0,146,174,1,1,133,1,0.9,1,1,2,1

# Dataset Shape

In [5]:
print("Rows and Columns:", df.shape)

Rows and Columns: (400, 14)

# Column Names

In [6]:
df.columns

Index(['age', 'sex', 'chest_pain_type', 'resting_blood_pressure',
       'cholesterol', 'fasting_blood_sugar', 'resting_ecg', 'max_heart_rate',
       'exercise_induced_angina', 'st_depression', 'st_slope',
       'num_major_vessels', 'thalassemia', 'heart_disease'],
      dtype='object')

# Dataset Information

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      400 non-null    int64
 1   sex                      400 non-null    int64
 2   chest_pain_type          400 non-null    int64
 3   resting_blood_pressure   400 non-null    int64
 4   cholesterol              400 non-null    int64
 5   fasting_blood_sugar      400 non-null    int64
 6   resting_ecg              400 non-null    int64
 7   max_heart_rate           400 non-null    int64
 8   exercise_induced_angina  400 non-null    int64
 9   st_depression            400 non-null    float64
 10  st_slope                 400 non-null    int64
 11  num_major_vessels        400 non-null    int64
 12  thalassemia              400 non-null    int64
 13  heart_disease            400 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 43.9 KB

# Statistical Summary

In [8]:
df.describe()

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,heart_disease
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,53.667500,0.662500,1.712500,123.630000,216.627500,0.140000,0.530000,146.717500,0.29250,0.753250,1.177500,0.677500,1.925000,0.555000
std,8.508403,0.473449,1.035628,16.567114,41.379941,0.347422,0.533678,21.104293,0.45548,0.772841,0.645784,0.889084,0.689611,0.497588
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,91.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,1.000000,112.000000,188.000000,0.000000,0.000000,132.000000,0.00000,0.200000,1.000000,0.000000,2.000000,0.000000
50%,54.000000,1.000000,2.000000,124.000000,216.000000,0.000000,1.000000,146.000000,0.00000,0.600000,1.000000,0.000000,2.000000,1.000000
75%,59.000000,1.000000,3.000000,135.000000,246.000000,0.000000,1.000000,161.000000,1.00000,0.900000,2.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,174.000000,336.000000,1.000000,2.000000,202.000000,1.00000,4.900000,2.000000,3.000000,3.000000,1.000000

In [9]:
df.describe(include="all")

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,heart_disease
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,53.667500,0.662500,1.712500,123.630000,216.627500,0.140000,0.530000,146.717500,0.29250,0.753250,1.177500,0.677500,1.925000,0.555000
std,8.508403,0.473449,1.035628,16.567114,41.379941,0.347422,0.533678,21.104293,0.45548,0.772841,0.645784,0.889084,0.689611,0.497588
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,91.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,1.000000,112.000000,188.000000,0.000000,0.000000,132.000000,0.00000,0.200000,1.000000,0.000000,2.000000,0.000000
50%,54.000000,1.000000,2.000000,124.000000,216.000000,0.000000,1.000000,146.000000,0.00000,0.600000,1.000000,0.000000,2.000000,1.000000
75%,59.000000,1.000000,3.000000,135.000000,246.000000,0.000000,1.000000,161.000000,1.00000,0.900000,2.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,174.000000,336.000000,1.000000,2.000000,202.000000,1.00000,4.900000,2.000000,3.000000,3.000000,1.000000

In [10]:
print("\nDataset Preview")
display(df.head())

print("\nRandom Sample")
display(df.sample(5))

Dataset Preview

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,heart_disease
0,58,1,1,134,246,0,0,155,0,0.4,1,1,2,1
1,52,0,2,112,245,0,0,143,1,0.1,0,0,3,1
2,59,0,2,126,196,0,0,162,1,1.1,1,0,1,1
3,67,1,1,165,201,0,0,180,0,0.4,2,0,2,0
4,51,1,0,146,174,1,1,133,1,0.9,1,1,2,1

Random Sample

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,heart_disease
245,50,1,3,98,214,0,1,122,0,2.5,2,1,2,1
48,57,1,0,118,175,0,1,144,0,0.9,1,0,2,1
0,58,1,1,134,246,0,0,155,0,0.4,1,1,2,1
53,59,0,2,107,211,0,0,200,0,0.2,1,2,2,0
138,61,0,2,143,272,0,1,126,0,0.7,1,0,2,0